### ISSUE TITLE
Multiple AWS environments and secrets

### ISSUE THREAD

**Issue by thanosexcite** [hashicorp/terraform-github-actions#33]
Hi there. I'm trying out the Github Actions integration with Terraform using this project and I came across the following limitation. My repo is using the "Directories" example at the end of https://www.terraform.io/docs/enterprise/workspaces/repo-structure.html . Each environment directory corresponds to a different AWS account.

But from what I found in github actions docs, it's not possible to use the same secret name on the same repo more than once, even if it will be used by a different github action workflow. So it's not possible to have a  `AWS_ACCESS_KEY_ID` secret for the QA env workflow and a different `AWS_ACCESS_KEY_ID` secret for use by the Staging env workflow.

So, is there a way to supply the secrets in a different way that will overcome this limitation in Github Actions or I should be looking at an alternative CI tool?

Thank you

**Comment by lkysow** [comment]
Hi, there's no way to overcome this issue with how the actions work right now. I'd recommend you fork these actions and then make your own changes:
* add two secrets: AWS_ACCESS_KEY_ID_DIR_1, AWS_ACCESS_KEY_ID_DIR_2
* add some detection logic that detects which directory you're in and then runs `export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_DIR_1"
* Instead of using `hashicorp/terraform-github-actions` point to your fork: `thanosexcite/terraform-github-actions` in your `.github/main.workflow`
