### ISSUE TITLE
Terraform Plan: comment not formatted correctly

### ISSUE THREAD

**Issue by alexbde** [hashicorp/terraform-github-actions#98]
Since terraform-github-actions@v0.5.x comments from terraform plan action are no longer formatted correctly.

See following screenshot. First comment is from terraform-github-actions/plan@v0.4.6, second comment is from terraform-github-actions@v0.5.2

![Terraform Plan Comment](https://user-images.githubusercontent.com/17784818/68130695-1780e080-ff1c-11e9-967a-c6e1d77f02e8.png)

**Comment by sudomateo** [comment]
Hello @alexbde. Are you able to send me the raw text of that comment?

**Comment by alexbde** [comment]
Much better but still missing colored highlighting of create/update/delete:

![Image](https://user-images.githubusercontent.com/17784818/68136040-e35ded80-ff24-11e9-8e5b-47afab138ee4.png)

**Comment by sudomateo** [comment]
@alexbde I pushed another change to that branch. Should be good to go now. I'm not a huge fan of the implementation honestly. In order to have GitHub highlight a diff, the `+` or `-` symbols need to be the first character on the line. As a result, the indentation will no longer be preserved if users wish to see colors in their comments.

**Comment by alexbde** [comment]
@sudomateo I understand. Indentation is more important than coloring so I'm fine with that. Thank you for quick solution! :)

**Comment by sudomateo** [comment]
Awesome. I'm going to fix the formatting but revert the highlight. Thank you for posting this issue!
